export const supabaseTables = {
  profiles: "profiles",
  princessProfiles: "princess_profiles",
  quests: "quests",
  questHistory: "quest_history",
  calendarEvents: "calendar_events",
  calendarReminders: "calendar_reminders",
  userProgress: "user_progress",
  dailyCompletions: "daily_completions",
  castleRooms: "castle_rooms",
  castleState: "castle_state",
  roomDecorations: "room_decorations",
  achievements: "achievements",
  userAchievements: "user_achievements",
  inventoryItems: "inventory_items",
  userTitles: "user_titles",
  serinConversations: "serin_conversations",
  serinMessages: "serin_messages",
  serinMemory: "serin_memory",
  contacts: "contacts",
  relationshipBook: "relationship_book",
  diaryDrafts: "diary_drafts",
} as const;

export type SupabaseTableName = (typeof supabaseTables)[keyof typeof supabaseTables];
