import { useEffect, useState } from 'react'
import { BellRing, Boxes, FileClock, LoaderCircle, Save, Settings2 } from 'lucide-react'
import { getAdminRuntime, saveAdminAnnouncement, saveAdminCatalogItem, saveAdminRelease, updateAdminRuntime, type AdminAnnouncement, type AdminCatalogItem, type AdminRelease, type AdminRuntimeData, type AdminRuntimeRow } from '../../services/adminService'

const emptyAnnouncement = (): AdminAnnouncement => ({ kind: 'notice', severity: 'info', title: '', message: '', platforms: ['web','ios','android'], starts_at: new Date().toISOString().slice(0,16), is_published: true, dismissible: true })
const emptyCatalog = (): AdminCatalogItem => ({ product_key: '', category: 'theme', title: '', description: '', price_krw: 0, entitlement_key: '', platforms: ['ios','android'], active: false, sort_order: 0, metadata: {} })
const emptyRelease = (runtime?: AdminRuntimeRow): AdminRelease => ({ version:'', title:'', items:[], platforms:['web','ios','android'], release_date:new Date().toISOString().slice(0,10), published_at:new Date().toISOString(), is_published:true, minimum_versions:runtime?.minimum_versions ?? {web:'0.1.0',ios:'1.0.0',android:'1.0.0'}, force_update:false })

export function AdminRuntimePanel() {
  const [data, setData] = useState<AdminRuntimeData | null>(null)
  const [runtime, setRuntime] = useState<AdminRuntimeRow | null>(null)
  const [announcement, setAnnouncement] = useState<AdminAnnouncement>(emptyAnnouncement)
  const [catalogItem, setCatalogItem] = useState<AdminCatalogItem>(emptyCatalog)
  const [release, setRelease] = useState<AdminRelease>(emptyRelease())
  const [releaseItems, setReleaseItems] = useState('')
  const [saving, setSaving] = useState(false)
  const [message, setMessage] = useState('')
  const load = async () => { const next = await getAdminRuntime(); setData(next); setRuntime(next.runtime) }
  useEffect(() => {
    let active = true
    void getAdminRuntime().then((next) => { if (active) { setData(next); setRuntime(next.runtime) } }).catch((error) => { if (active) setMessage(error instanceof Error ? error.message : '운영 설정을 불러오지 못했습니다.') })
    return () => { active = false }
  }, [])
  const mutateRuntime = (change: Partial<AdminRuntimeRow>) => setRuntime((current) => current ? { ...current, ...change } : current)
  const saveRuntime = async () => { if (!runtime) return; setSaving(true); setMessage(''); try { const result = await updateAdminRuntime(runtime); setRuntime(result.runtime); setMessage('공통 운영 설정을 저장했습니다. 앱에는 최대 5분 이내 반영됩니다.') } catch (error) { setMessage(error instanceof Error ? error.message : '운영 설정을 저장하지 못했습니다.') } finally { setSaving(false) } }
  const saveNotice = async () => { setSaving(true); setMessage(''); try { await saveAdminAnnouncement({ ...announcement, starts_at: new Date(announcement.starts_at).toISOString(), ends_at: announcement.ends_at ? new Date(announcement.ends_at).toISOString() : null }); await load(); setAnnouncement(emptyAnnouncement()); setMessage('공지를 게시했습니다.') } catch (error) { setMessage(error instanceof Error ? error.message : '공지를 저장하지 못했습니다.') } finally { setSaving(false) } }
  const saveCatalog = async () => { setSaving(true); setMessage(''); try { await saveAdminCatalogItem(catalogItem); await load(); setCatalogItem(emptyCatalog()); setMessage('테마·위젯 상품을 저장했습니다.') } catch (error) { setMessage(error instanceof Error ? error.message : '상품을 저장하지 못했습니다.') } finally { setSaving(false) } }
  const saveRelease = async () => { if (!runtime) return; setSaving(true); setMessage(''); try { await saveAdminRelease({...release,items:releaseItems.split('\n').map((item)=>item.trim()).filter(Boolean),minimum_versions:runtime.minimum_versions}); await load(); setRelease(emptyRelease(runtime)); setReleaseItems(''); setMessage('공통 패치노트를 저장했습니다.') } catch (error) { setMessage(error instanceof Error?error.message:'패치노트를 저장하지 못했습니다.') } finally { setSaving(false) } }
  if (!runtime || !data) return <article className="panel glass-panel admin-runtime-loading"><LoaderCircle className="spin"/><span>{message || '공통 운영 설정을 불러오는 중…'}</span></article>
  const flags = runtime.feature_flags
  return <section className="admin-runtime">
    <header className="panel glass-panel admin-runtime-hero"><div><span className="eyebrow">LIVE OPERATIONS</span><h2>공통 업데이트 시스템</h2><p>웹·iOS·Android가 재심사 없이 함께 읽는 설정입니다.</p></div><Settings2 size={24}/></header>
    {message && <p className="admin-message" role="status">{message}</p>}
    <article className="panel glass-panel admin-runtime-card">
      <header><div><Settings2/><h3>버전·점검·기능</h3></div><button className="primary" onClick={() => void saveRuntime()} disabled={saving}><Save size={14}/>전체 설정 저장</button></header>
      <div className="admin-runtime-grid"><label>서버 API 버전<input value={runtime.api_version} onChange={(event) => mutateRuntime({ api_version:event.target.value })}/></label><label>웹 최소 버전<input value={runtime.minimum_versions.web} onChange={(event) => mutateRuntime({ minimum_versions:{...runtime.minimum_versions,web:event.target.value} })}/></label><label>iOS 최소 버전<input value={runtime.minimum_versions.ios} onChange={(event) => mutateRuntime({ minimum_versions:{...runtime.minimum_versions,ios:event.target.value} })}/></label><label>Android 최소 버전<input value={runtime.minimum_versions.android} onChange={(event) => mutateRuntime({ minimum_versions:{...runtime.minimum_versions,android:event.target.value} })}/></label></div>
      <div className="admin-toggle-row"><Toggle label="강제 업데이트" checked={runtime.force_update} onChange={(value) => mutateRuntime({force_update:value})}/><Toggle label="점검 안내" checked={runtime.maintenance.enabled} onChange={(value) => mutateRuntime({maintenance:{...runtime.maintenance,enabled:value}})}/><Toggle label="화면 차단 점검" checked={runtime.maintenance.blocking} onChange={(value) => mutateRuntime({maintenance:{...runtime.maintenance,blocking:value}})}/></div>
      <div className="admin-runtime-grid two"><label>점검 제목<input value={runtime.maintenance.title} onChange={(event) => mutateRuntime({maintenance:{...runtime.maintenance,title:event.target.value}})}/></label><label>점검 안내<textarea value={runtime.maintenance.message} onChange={(event) => mutateRuntime({maintenance:{...runtime.maintenance,message:event.target.value}})}/></label></div>
      <h4>기능 활성화</h4><div className="admin-toggle-row">{Object.entries(flags).map(([key, enabled]) => <Toggle key={key} label={key} checked={enabled} onChange={(value) => mutateRuntime({feature_flags:{...flags,[key]:value}})}/>)}</div>
      <h4>AI 포인트 정책</h4><div className="admin-tier-grid">{(['free','royal','royal_ai'] as const).map((key) => { const tier = runtime.ai_point_policy.tiers[key]; return <fieldset key={key}><legend>{key}</legend><label>월 포인트<input type="number" value={tier.monthlyPoints} onChange={(event) => mutateRuntime({ai_point_policy:{...runtime.ai_point_policy,tiers:{...runtime.ai_point_policy.tiers,[key]:{...tier,monthlyPoints:Number(event.target.value)}}}})}/></label><label>하루 요청<input type="number" value={tier.dailyRequests} onChange={(event) => mutateRuntime({ai_point_policy:{...runtime.ai_point_policy,tiers:{...runtime.ai_point_policy.tiers,[key]:{...tier,dailyRequests:Number(event.target.value)}}}})}/></label><label>가입 포인트<input type="number" value={tier.signupBonus} onChange={(event) => mutateRuntime({ai_point_policy:{...runtime.ai_point_policy,tiers:{...runtime.ai_point_policy.tiers,[key]:{...tier,signupBonus:Number(event.target.value)}}}})}/></label></fieldset>})}</div>
      <h4>요금제와 체험</h4><label className="admin-trial">무료 체험 일수<input type="number" value={runtime.plan_catalog.trialDays} onChange={(event) => mutateRuntime({plan_catalog:{...runtime.plan_catalog,trialDays:Number(event.target.value)}})}/></label><div className="admin-tier-grid">{(['free','royal','royal_ai'] as const).map((key) => { const plan = runtime.plan_catalog.plans[key]; return <fieldset key={key}><legend>{plan.name}</legend><label>월 가격<input type="number" value={plan.monthlyPriceKrw} onChange={(event) => mutateRuntime({plan_catalog:{...runtime.plan_catalog,plans:{...runtime.plan_catalog.plans,[key]:{...plan,monthlyPriceKrw:Number(event.target.value)}}}})}/></label><label>연 가격<input type="number" value={plan.annualPriceKrw} onChange={(event) => mutateRuntime({plan_catalog:{...runtime.plan_catalog,plans:{...runtime.plan_catalog.plans,[key]:{...plan,annualPriceKrw:Number(event.target.value)}}}})}/></label></fieldset>})}</div>
    </article>
    <div className="admin-runtime-columns">
      <article className="panel glass-panel admin-runtime-card"><header><div><BellRing/><h3>공지 게시</h3></div></header><label>제목<input value={announcement.title} onChange={(event) => setAnnouncement({...announcement,title:event.target.value})}/></label><label>내용<textarea value={announcement.message} onChange={(event) => setAnnouncement({...announcement,message:event.target.value})}/></label><div className="admin-runtime-grid two"><label>종류<select value={announcement.kind} onChange={(event) => setAnnouncement({...announcement,kind:event.target.value as AdminAnnouncement['kind']})}><option value="notice">공지</option><option value="maintenance">점검</option><option value="event">이벤트</option></select></label><label>중요도<select value={announcement.severity} onChange={(event) => setAnnouncement({...announcement,severity:event.target.value as AdminAnnouncement['severity']})}><option value="info">안내</option><option value="warning">주의</option><option value="critical">긴급</option></select></label><label>시작<input type="datetime-local" value={announcement.starts_at.slice(0,16)} onChange={(event) => setAnnouncement({...announcement,starts_at:event.target.value})}/></label><label>종료 · 선택<input type="datetime-local" value={announcement.ends_at?.slice(0,16) ?? ''} onChange={(event) => setAnnouncement({...announcement,ends_at:event.target.value || null})}/></label></div><button className="primary" disabled={saving || !announcement.title.trim() || !announcement.message.trim()} onClick={() => void saveNotice()}>공지 저장</button><div className="admin-runtime-list">{data.announcements.slice(0,5).map((item) => <button key={item.id} onClick={() => setAnnouncement({...item,starts_at:new Date(item.starts_at).toISOString().slice(0,16),ends_at:item.ends_at?new Date(item.ends_at).toISOString().slice(0,16):null})}><b>{item.title}</b><small>{item.is_published?'게시 중':'비공개'} · {item.kind}</small></button>)}</div></article>
      <article className="panel glass-panel admin-runtime-card"><header><div><Boxes/><h3>테마·위젯 상품</h3></div></header><label>상품 키<input value={catalogItem.product_key} onChange={(event) => setCatalogItem({...catalogItem,product_key:event.target.value})} placeholder="theme.rose_palace"/></label><label>상품명<input value={catalogItem.title} onChange={(event) => setCatalogItem({...catalogItem,title:event.target.value})}/></label><label>설명<textarea value={catalogItem.description} onChange={(event) => setCatalogItem({...catalogItem,description:event.target.value})}/></label><div className="admin-runtime-grid two"><label>종류<select value={catalogItem.category} onChange={(event) => setCatalogItem({...catalogItem,category:event.target.value as AdminCatalogItem['category']})}><option value="theme">테마</option><option value="widget">위젯</option></select></label><label>가격<input type="number" value={catalogItem.price_krw} onChange={(event) => setCatalogItem({...catalogItem,price_krw:Number(event.target.value)})}/></label><label>권한 키<input value={catalogItem.entitlement_key} onChange={(event) => setCatalogItem({...catalogItem,entitlement_key:event.target.value})}/></label><Toggle label="판매 활성화" checked={catalogItem.active} onChange={(value) => setCatalogItem({...catalogItem,active:value})}/></div><button className="primary" disabled={saving || !catalogItem.product_key.trim() || !catalogItem.title.trim() || !catalogItem.entitlement_key.trim()} onClick={() => void saveCatalog()}>상품 저장</button><div className="admin-runtime-list">{data.catalog.slice(0,8).map((item) => <button key={item.product_key} onClick={() => setCatalogItem(item)}><b>{item.title}</b><small>{item.active?'판매 중':'비활성'} · {item.price_krw.toLocaleString()}원</small></button>)}</div></article>
    </div>
    <article className="panel glass-panel admin-runtime-card"><header><div><FileClock/><h3>공통 패치노트</h3></div></header><div className="admin-runtime-grid"><label>버전<input value={release.version} onChange={(event)=>setRelease({...release,version:event.target.value})} placeholder="0.6.0"/></label><label>제목<input value={release.title} onChange={(event)=>setRelease({...release,title:event.target.value})}/></label><label>출시일<input type="date" value={release.release_date} onChange={(event)=>setRelease({...release,release_date:event.target.value})}/></label><Toggle label="즉시 게시" checked={release.is_published} onChange={(value)=>setRelease({...release,is_published:value})}/></div><label>변경 항목 · 한 줄에 하나<textarea value={releaseItems} onChange={(event)=>setReleaseItems(event.target.value)} placeholder={'새 기능을 추가했어요.\n오류를 수정했어요.'}/></label><button className="primary" disabled={saving||!release.version.trim()||!release.title.trim()||!releaseItems.trim()} onClick={()=>void saveRelease()}>패치노트 저장</button><div className="admin-runtime-list">{data.releases.slice(0,8).map((item)=><button key={item.version} onClick={()=>{setRelease(item);setReleaseItems(item.items.join('\n'))}}><b>v{item.version} · {item.title}</b><small>{item.is_published?'게시 중':'비공개'} · {item.release_date}</small></button>)}</div></article>
  </section>
}

function Toggle({label,checked,onChange}:{label:string;checked:boolean;onChange:(value:boolean)=>void}) { return <label className="admin-toggle"><input type="checkbox" checked={checked} onChange={(event)=>onChange(event.target.checked)}/><span>{label}</span></label> }
